name: Check, build and push Docker image

on:
  push:
    branches:
      - main
      - development

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  quality-check:
    name: Quality Check
    uses: ./.github/workflows/quality.yml

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: quality-check
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set lowercase image name
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set safe branch name
        run: echo "SAFE_BRANCH_NAME=$(echo '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9._-]/-/g')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup sbt
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: "1.11.7"

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            project/target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Build Docker image with sbt
        run: sbt "srag-infrastructure/Docker/publishLocal"

      - name: Tag and push Docker image
        run: |
          # Get the actual image name from sbt Docker plugin
          LOCAL_IMAGE_NAME=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep srag | head -1)
          echo "Local image: $LOCAL_IMAGE_NAME"

          # Create proper tags for GitHub Container Registry
          NEW_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.SAFE_BRANCH_NAME }}-${{ github.sha }}"
          docker tag "$LOCAL_IMAGE_NAME" "$NEW_TAG"
          docker push "$NEW_TAG"

          # Tag as latest for main branch
          if [ "${{ github.ref_name }}" = "main" ]; then
            LATEST_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest"
            docker tag "$LOCAL_IMAGE_NAME" "$LATEST_TAG"
            docker push "$LATEST_TAG"
          fi
